// packages/react/src/Gallery.tsx
import React, {
    Fragment,
    useState,
    useRef,
    useEffect,
    Component
} from "react";
import './assets/css/gallery.css';


function imageGallery() {

    const gallery_nav_li:HTMLCollectionOf<HTMLLIElement> = document.getElementsByTagName("li");

   const gallery_img:HTMLCollectionOf<HTMLImageElement> = document.getElementsByTagName("img");
   
    for(let x = 0; x < gallery_nav_li.length; x++) {
	let navli:any = gallery_nav_li[x];
        navli.onclick = function() {
            
            var myid = navli.getAttribute("id");
            
            for(let z = 0; z < gallery_nav_li.length; z++) {
                gallery_nav_li[z].removeAttribute("class");
            };
            
            navli.setAttribute("class", "g-n-active");
            
            for(let y = 0; y < gallery_img.length; y++) {
                gallery_img[y].removeAttribute("class");
                var the_image:any = document.getElementById(myid + "-img");
                the_image.setAttribute("class", "g-active");
            };
        };
    };
};

imageGallery();



return ( <Fragment>

<section className="dark:bg-gray-800 dark:text-white">

<div class="gallery clearfix">
  <div class="gallery-container clearfix">
    <img  src="assets/img/1.jpg" id="start" />
    <img  src="assets/img/2.jpg" id="first-img" />
    <img  src="assets/img/3.jpg" id="second-img" />
    <img  src="assets/img/4.jpg" id="third-img" />
    <img  src="assets/img/5.jpg" id="fourth-img" />
    <img  src="assets/img/7.jpg" id="fifth-img" />
    <img  src="assets/img/8.jpg" id="sixth-img" />
    <img  src="assets/img/9.jpg" id="seventh-img" />
    <img  src="assets/img/6.jpg" class="g-active" id="eighth-img" />
  </div>
  <nav>
    <ul class="gallery-nav">
      <li class="g-n-active" id="fifth"></li>
      <li id="first"></li>
      <li id="second"></li>
      <li id="third"></li>
      <li id="fourth"></li>
      <li id="fifth"></li>
      <li id="sixth"></li>
      <li id="seventh"></li>
      <li id="eighth"></li>
    </ul>
  </nav>
</div>

</section>

  </Fragment>
  );
}

export default Gallery;

// packages/angular/projects/gallery/src/lib/gallery.component.ts
import {
    Input,
    ChangeDetectorRef,
    ViewChild,
    ViewEncapsulation
} from '@angular/core';
import {
    Component,
    OnInit,
    ElementRef,
    Renderer2,
    Inject
} from '@angular/core';
import {
    Pipe,
    PipeTransform,
    SecurityContext
} from '@angular/core';
import {
    DomSanitizer,
    SafeHtml,
    SafeStyle,
    SafeScript,
    SafeUrl,
    SafeResourceUrl
} from '@angular/platform-browser';
import {
    catchError
} from 'rxjs/operators';
import {
    DOCUMENT
} from '@angular/common';
import {
    HttpEvent,
    HttpEventType,
    HttpErrorResponse,
    HttpResponse,
    HttpClient
} from '@angular/common/http';
import {
    Observable
} from 'rxjs';


@Component({
    selector: 'progress-up',
    templateUrl: 'progress-up.component.html',
    styleUrls: [
        './progress-up.component.css'
    ],
    encapsulation: ViewEncapsulation.None
})

export class ProgressUpComponent {


    darkControls = `
    <span class="hidden dark:inline">&#127774;</span>
    <span class="inline dark:hidden">&#127769; </span>
  `;

    configVals1 = '&#128202; Progress type';
   uploadFileList: File[] = [];
    uploadFileInfos: fileInfo[] = [];
    errInfos: errInfo[] = [];
    disableUpload = true;
    thumbNailsDone = false;
    isDragged = false;

    progressBars: any[] = [];
    details = '';
    statsTable: statsTableType[] = [];

    constructor(private http: HttpClient) {}

    darkMode() {
        document.body.classList.toggle('dark');
    }

imageGallery() {
    var gallery_nav_li = document.getElementsByTagName("li");
    var gallery_img = document.getElementsByTagName("img");
    
    for(x = 0; x < gallery_nav_li.length; x++) {
        gallery_nav_li[x].onclick = function() {
            
            var myid = this.getAttribute("id");
            
            for(z = 0; z < gallery_nav_li.length; z++) {
                gallery_nav_li[z].removeAttribute("class", "g-n-active");
            };
            
            this.setAttribute("class", "g-n-active");
            
            for(y = 0; y < gallery_img.length; y++) {
                gallery_img[y].removeAttribute("class", "g-active");
                var the_image = document.getElementById(myid + "-img");
                the_image.setAttribute("class", "g-active");
            };
        };
    };
};

imageGallery();

}


<div class="gallery clearfix">
  <div class="gallery-container clearfix">
    <img  src="img/1.jpg" id="start" />
    <img  src="img/2.jpg" id="first-img" />
    <img  src="img/3.jpg" id="second-img" />
    <img  src="img/4.jpg" id="third-img" />
    <img  src="img/5.jpg" id="fourth-img" />
    <img  src="img/7.jpg" id="fifth-img" />
    <img  src="img/8.jpg" id="sixth-img" />
    <img  src="img/9.jpg" id="seventh-img" />
    <img  src="img/6.jpg" class="g-active" id="eighth-img" />
  </div>
  <nav>
    <ul class="gallery-nav">
      <li class="g-n-active" id="fifth"></li>
      <li id="first"></li>
      <li id="second"></li>
      <li id="third"></li>
      <li id="fourth"></li>
      <li id="fifth"></li>
      <li id="sixth"></li>
      <li id="seventh"></li>
      <li id="eighth"></li>
    </ul>
  </nav>
</div>
