// packages/svelte/src/lib/Blackgallery.svelte


<script lang='ts'>

import {
    writable
} from "svelte/store";
const imageList  = writable([]);


let fetchJson = fetch('config.json').then(res => res.json()).
	then((res) => ( imageList.set(res)));

const emptyMsg = `
		<h2> Please configure by inserting images and caption
		using images.js file </h2>
		
		<pre>
		 const images = [{
        		"src": "https://source.unsplash.com/featured/800x600",
        		"alt": "Beautiful scenery I "
    		},
    		{
        		"src": "https://source.unsplash.com/featured/700x500",
        		"alt": "Beautiful scenery II "
    		}
		];
		</pre>
	`;


const switchImage = (idx) => {
    for (let i = 0; i < $imageList.length; i++) {
        $imageList[i].isActive = false;
    }
    $imageList[idx].isActive = true;

    console.log(idx);
    console.log("I am switching image now");
    imageList.set([...$imageList]);
};

   </script>


 <h1> Blackgallery </h1>
<!-- XXX This is the gallery switcher -->
  <nav>
    <ul id="listImages" class="gallery-nav"> 
  {#each $imageList as {src, alt, isActive}, index } 
   <li id={index} on:click= {() => switchImage(index)} class="{ isActive ?  'switch-image' : ''}" >
 </li>
  {/each}
    </ul>
 
  </nav>


<section class="gallery clearfix">
  <!-- Images are shown in this container on switching -->
  <div id="galleryArea" class="gallery-container clearfix">
	{#if $imageList.length == 0}
		{@html emptyMsg}
	{/if}
  {#each $imageList as {src, alt, isActive}, index } 
	{#if index == 0}
	<figure id="start"  style="opacity:{ isActive ? '1' : '0'}" class="gallery-display show-image" >
		<img  src={src}  />
  		<figcaption>{alt}</figcaption>
	</figure>

	{:else}
	<figure id={index +'-img'} class="{ isActive ?  'gallery-display show-image':'gallery-display'}" >
		<img  src={src}  />
  		<figcaption>{alt}</figcaption>
	</figure>
	{/if}

  {/each}
  </div>

</section>

// packages/angular/projects/blackgallery/src/lib/blackgallery.component.ts
import {
    Input,
    ChangeDetectorRef,
    ViewChild,
    ViewEncapsulation
} from '@angular/core';
import {
    Component,
    OnInit,
    ElementRef,
    Renderer2,
    Inject
} from '@angular/core';
import {
    Pipe,
    PipeTransform,
    SecurityContext
} from '@angular/core';
import {
    DomSanitizer,
    SafeHtml,
    SafeStyle,
    SafeScript,
    SafeUrl,
    SafeResourceUrl
}  from '@angular/platform-browser';
import {
    catchError
} from 'rxjs/operators';
import {
    DOCUMENT
} from '@angular/common';
import {
    HttpEvent,
    HttpEventType,
    HttpErrorResponse,
    HttpResponse,
    HttpClient
} from '@angular/common/http';
import {
    Observable
} from 'rxjs';


@Component({
    selector: 'blackgallery',
    templateUrl: 'blackgallery.component.html',
    styleUrls: [
        './blackgallery.component.css'
    ],
    encapsulation: ViewEncapsulation.None
})

export class BlackgalleryComponent {


    imageList: any[] = [];

    constructor(private http: HttpClient) {
    fetch('/assets/config.json').then(
     (res) => res.json())
    .then((res) => {
	this.imageList = res;
        this.switchImage(0);	
	}); 
    }


     emptyMsg:string = `		
	<h2> Please configure by inserting images and caption
		using images.js file </h2>
		
		<pre>
		 const images = [{
        		"src": "https://source.unsplash.com/featured/800x600",
        		"alt": "Beautiful scenery I "
    		},
    		{
        		"src": "https://source.unsplash.com/featured/700x500",
        		"alt": "Beautiful scenery II "
    		}
		];
		</pre>
	`;
	switchImage(idx: number) {
		for(let i = 0; i < this.imageList.length; i++) {

			this.imageList[i].isActive = false;
		}
		this.imageList[idx].isActive = true;
		console.log(idx);
		console.log("I am switching image now");
	}
}



 <h1> Blackgallery </h1>
<!-- XXX This is the gallery switcher -->
  <nav>
    <ul id="listImages" class="gallery-nav"> 
   <li *ngFor="let img of imageList;index as idx"
id={{idx}} (click) = "switchImage(idx)" [ngClass]=" img.isActive ?  'switch-image' : ''" >
 </li>
    </ul>
  </nav>

  <!-- Images are shown in this container on switching -->
  <div  class="gallery-container">

     <div *ngIf="imageList.length == 0">
	{{emptyMsg}}
     </div>
     <div *ngFor="let img of imageList;index as idx">

	<div *ngIf="idx == 0 ; else El" >
	<figure id="start" [ngStyle]="img.isActive ? {'opacity': '1'} : {'opacity': '0'}" class="gallery-display show-image" >
  		<figcaption>{{img.alt}}</figcaption>
		<img  src={{img.src}}  />
	</figure>
	</div>

	<ng-template #El>
	<figure id="idx +'-img'" [ngClass] ="img.isActive ?  'gallery-display show-image':'gallery-display'" >
  		<figcaption>{{img.alt}}</figcaption>
		<img  src={{img.src}}  />
	</figure>
	</ng-template>
    </div>
  </div>
