// packages/svelte/src/lib/Blackgallery.svelte


<script lang='ts'>

import {
    writable
} from "svelte/store";
const imageList  = writable([]);


let fetchJson = fetch('config.json').then(res => res.json()).
	then((res) => ( imageList.set(res)));

const emptyMsg = `
		<h2> Please configure by inserting images and caption
		using images.js file </h2>
		
		<pre>
		 const images = [{
        		"src": "https://source.unsplash.com/featured/800x600",
        		"alt": "Beautiful scenery I "
    		},
    		{
        		"src": "https://source.unsplash.com/featured/700x500",
        		"alt": "Beautiful scenery II "
    		}
		];
		</pre>
	`;


const switchImage = (idx) => {
    for (let i = 0; i < $imageList.length; i++) {
        $imageList[i].isActive = false;
    }
    $imageList[idx].isActive = true;

    console.log(idx);
    console.log("I am switching image now");
    imageList.set([...$imageList]);
};

   </script>


 <h1> Blackgallery </h1>
<!-- XXX This is the gallery switcher -->
  <nav>
    <ul id="listImages" class="gallery-nav"> 
  {#each $imageList as {src, alt, isActive}, index } 
   <li id={index} on:click= {() => switchImage(index)} class="{ isActive ?  'switch-image' : ''}" >
 </li>
  {/each}
    </ul>
 
  </nav>


<section class="gallery clearfix">
  <!-- Images are shown in this container on switching -->
  <div id="galleryArea" class="gallery-container clearfix">
	{#if $imageList.length == 0}
		{@html emptyMsg}
	{/if}
  {#each $imageList as {src, alt, isActive}, index } 
	{#if index == 0}
	<figure id="start"  style="opacity:{ isActive ? '1' : '0'}" class="gallery-display show-image" >
		<img  src={src}  />
  		<figcaption>{alt}</figcaption>
	</figure>

	{:else}
	<figure id={index +'-img'} class="{ isActive ?  'gallery-display show-image':'gallery-display'}" >
		<img  src={src}  />
  		<figcaption>{alt}</figcaption>
	</figure>
	{/if}

  {/each}
  </div>

</section>

// packages/vue/src/Blackgallery.vue
<script lang="ts">
 export default {
     data() {
         return {
             imageList: [],
	     emptyMsg: `

		<h2> Please configure by inserting images and caption
		using images.js file </h2>
		
		<pre>
		 const images = [{
        		"src": "https://source.unsplash.com/featured/800x600",
        		"alt": "Beautiful scenery I "
    		},
    		{
        		"src": "https://source.unsplash.com/featured/700x500",
        		"alt": "Beautiful scenery II "
    		}
		];
	  `
         }
     },
     methods: {

getRuntimeConfig () {
 fetch('/config.json').then(
	res => res.json()).then(
	(res) => {this.imageList = res;
	 this.switchImage(0);
	});
},

         switchImage(idx) {
	     
             for (let i = 0; i < this.imageList.length; i++) {
                 this.imageList[i].isActive = false;
             }
             this.imageList[idx].isActive = true;
             console.log(idx);
             console.log("I am switching image now");
         }
     },
     created() {
	 this.getRuntimeConfig();
     }
     
 }
</script>

<template>

 <h1> Blackgallery </h1>
  <!-- XXX This is the gallery switcher -->
    <ul class="gallery-nav"> 
       <li v-for="(item, id) in imageList" :key="id" :id="id"
@click="switchImage(id)" v-bind:class="(item.isActive)? 'switch-image':''" ></li>
    </ul>


  <!-- Images are shown in this container on switching -->
  <div  class="gallery-container">

     <div v-html="emptyMsg" v-if="imageList.length == 0">
     </div>
    <div v-for="(item,id) in imageList" :key="id">

     <div v-if="id == 0">
	<figure id="start" :style="[ item.isActive ? {opacity: 1} : {opacity: 0}]" class="gallery-display show-image" >
  		<figcaption>{{item.alt}}</figcaption>
		<img  :src="item.src"  />
	</figure>
      </div>

      <div v-else>
	<figure :id="id+'-img'" v-bind:class = "(item.isActive)? 'gallery-display show-image':'gallery-display'" >
  		<figcaption>{{item.alt}}</figcaption>
		<img  :src="item.src"  />
	</figure>
      </div>

     </div>

</div>

</template>

<style scoped>
@import url("https://cdn.jsdelivr.net/gh/girish1729/blackgallery/source/assets/css/gallery.css");
</style>
