// packages/react/src/Blackgallery.tsx
import React, {
    Fragment,
    useState,
    useEffect,
    Component
} from "react";
import './style.css';

interface img {
    src: string;
    alt: string;
    isActive: boolean;
};
 
function Blackgallery() {

    let [imgList, setImageList] = useState < Array < img >> ( [] );

useEffect(() => {
    fetch("/config.json")
      .then((res) => res.json())
      .then((images) => {

        	setImageList(images);
      });
}, []);
  

    const emptyMsg = `
<h2> Please configure by inserting images and caption
		using images.js file </h2>
		
		<pre>
		 const images = [{
        		"src": "https://source.unsplash.com/featured/800x600",
        		"alt": "Beautiful scenery I "
    		},
    		{
        		"src": "https://source.unsplash.com/featured/700x500",
        		"alt": "Beautiful scenery II "
    		}
		];
		</pre>
	`;


const	switchImage = (idx: number) => {
		for(let i = 0; i < imgList.length; i++) {
			imgList[i].isActive = false;
        	setImageList(prev => {
                    let newState = [...prev];
                    newState[i] = imgList[i];
                    return newState;
                });

		}
		imgList[idx].isActive = true;
		console.log(imgList[idx].isActive);
		console.log("I am switching image now");
        	setImageList(prev => {
                    let newState = [...prev];
                    newState[idx] = imgList[idx];
                    return newState;
                });
	};

return ( <Fragment>

 
 <h1> Blackgallery </h1>
    <ul className="gallery-nav"> 
{imgList.length > 0
  ? (
  imgList.map(({src, alt, isActive}, index) => (
       <li className={isActive ? "switch-image": " "} key={index}
id={String(index)} onClick={() => switchImage(index)}  ></li>
))
):<br/>}
    </ul>

  <div  className="gallery-container">


{imgList.length > 0
  ? (
  imgList.map(({src, alt, isActive}, index) => {

    if(index == 0)  {

	return <figure key={index} id="start" style={{ opacity : isActive ? '1': '0'}}
className="gallery-display show-image" >
		<img  src={src}  />
  		<figcaption>{alt}</figcaption>
	</figure>
	 } else {
	return <figure key={index} id={index +'-img'} className={isActive ? "gallery-display show-image":"gallery-display"} >
		<img  src={src}  />
  		<figcaption>{alt}</figcaption>
	</figure>
      }

}))

: (

	<div dangerouslySetInnerHTML={{__html: emptyMsg}}></div>


)}

</div>



  </Fragment>
  );
}

export default Blackgallery;

// packages/svelte/src/lib/Blackgallery.svelte


<script lang='ts'>

import {
    writable
} from "svelte/store";
const imageList  = writable([]);


let fetchJson = fetch('config.json').then(res => res.json()).
	then((res) => ( imageList.set(res)));

const emptyMsg = `
		<h2> Please configure by inserting images and caption
		using images.js file </h2>
		
		<pre>
		 const images = [{
        		"src": "https://source.unsplash.com/featured/800x600",
        		"alt": "Beautiful scenery I "
    		},
    		{
        		"src": "https://source.unsplash.com/featured/700x500",
        		"alt": "Beautiful scenery II "
    		}
		];
		</pre>
	`;


const switchImage = (idx) => {
    for (let i = 0; i < $imageList.length; i++) {
        $imageList[i].isActive = false;
    }
    $imageList[idx].isActive = true;

    console.log(idx);
    console.log("I am switching image now");
    imageList.set([...$imageList]);
};

   </script>


 <h1> Blackgallery </h1>
<!-- XXX This is the gallery switcher -->
  <nav>
    <ul id="listImages" class="gallery-nav"> 
  {#each $imageList as {src, alt, isActive}, index } 
   <li id={index} on:click= {() => switchImage(index)} class="{ isActive ?  'switch-image' : ''}" >
 </li>
  {/each}
    </ul>
 
  </nav>


<section class="gallery clearfix">
  <!-- Images are shown in this container on switching -->
  <div id="galleryArea" class="gallery-container clearfix">
	{#if $imageList.length == 0}
		{@html emptyMsg}
	{/if}
  {#each $imageList as {src, alt, isActive}, index } 
	{#if index == 0}
	<figure id="start"  style="opacity:{ isActive ? '1' : '0'}" class="gallery-display show-image" >
		<img  src={src}  />
  		<figcaption>{alt}</figcaption>
	</figure>

	{:else}
	<figure id={index +'-img'} class="{ isActive ?  'gallery-display show-image':'gallery-display'}" >
		<img  src={src}  />
  		<figcaption>{alt}</figcaption>
	</figure>
	{/if}

  {/each}
  </div>

</section>
